-- =============================================================================
-- V1 — Baseline do schema do Almoxarifado (gerado a partir das entidades JPA,
-- dialeto PostgreSQL; compatível com H2 em MODE=PostgreSQL para dev).
-- Padronização do ecossistema FPTO: migração de ddl-auto=update para Flyway.
-- =============================================================================

create table area (
    id bigint generated by default as identity,
    sigla varchar(5) not null unique,
    nome varchar(100) not null unique,
    descricao varchar(255),
    primary key (id)
);

create table subcategoria (
    id bigint generated by default as identity,
    area_id bigint not null,
    sigla varchar(5) not null,
    nome varchar(100) not null,
    descricao varchar(255),
    proximo_sequencial integer not null,
    primary key (id),
    constraint uk_subcategoria_area_sigla unique (area_id, sigla)
);

create table material (
    id bigint generated by default as identity,
    subcategoria_id bigint not null,
    codigo_sku varchar(50) unique,
    nome varchar(150) not null,
    unidade_medida varchar(30),
    estoque_atual integer not null,
    estoque_minimo integer not null,
    valor_unitario numeric(12,2),
    primary key (id)
);

create table setor (
    id bigint generated by default as identity,
    nome varchar(120) not null,
    responsavel varchar(120) not null,
    codigo_centro_custo varchar(30),
    primary key (id)
);

create table movimentacao (
    id bigint generated by default as identity,
    material_id bigint not null,
    setor_destino_id bigint,
    tipo varchar(20) not null check ((tipo in ('ENTRADA','SAIDA','COMPRA_DIRETA'))),
    status varchar(25) not null check ((status in ('PENDENTE_APROVACAO','APROVADO','ENTREGUE','REJEITADO'))),
    quantidade integer not null,
    data timestamp(6) not null,
    nota_fiscal varchar(50),
    retirado_por varchar(120),
    fornecedor varchar(150),
    primary key (id)
);

create table compra (
    id bigint generated by default as identity,
    setor_solicitante_id bigint,
    tipo varchar(15) not null check ((tipo in ('DIRETA','ESTOQUE'))),
    status varchar(25) not null check ((status in ('AGUARDANDO_COMPRA','COMPRA_REALIZADA','CANCELADA'))),
    valor_estimado numeric(12,2) not null,
    valor_real_final numeric(12,2),
    data_solicitacao timestamp(6) not null,
    data_recebimento timestamp(6),
    numero_nota_fiscal varchar(50),
    fornecedor varchar(150),
    observacao varchar(200),
    primary key (id)
);

create table item_compra (
    id bigint generated by default as identity,
    compra_id bigint not null,
    material_id bigint not null,
    quantidade integer not null,
    valor_unitario numeric(12,2) not null,
    primary key (id)
);

create table anexo_compra (
    id bigint generated by default as identity,
    compra_id bigint not null,
    tipo varchar(20) not null check ((tipo in ('SOLICITACAO','NOTA_FISCAL'))),
    nome_original varchar(255) not null,
    caminho_armazenado varchar(500) not null,
    content_type varchar(100),
    tamanho_bytes bigint,
    data_upload timestamp(6) not null,
    primary key (id)
);

-- Chaves estrangeiras
alter table subcategoria add constraint fk_subcategoria_area foreign key (area_id) references area;
alter table material add constraint fk_material_subcategoria foreign key (subcategoria_id) references subcategoria;
alter table movimentacao add constraint fk_movimentacao_material foreign key (material_id) references material;
alter table movimentacao add constraint fk_movimentacao_setor_destino foreign key (setor_destino_id) references setor;
alter table compra add constraint fk_compra_setor_solicitante foreign key (setor_solicitante_id) references setor;
alter table item_compra add constraint fk_item_compra_compra foreign key (compra_id) references compra;
alter table item_compra add constraint fk_item_compra_material foreign key (material_id) references material;
alter table anexo_compra add constraint fk_anexo_compra_compra foreign key (compra_id) references compra;
