-- ============================================================================
-- V1 - Schema inicial do Almoxarifado (PostgreSQL).
--
-- REGRAS DESTA MIGRATION (contrato do deploy):
--   * Estrutura APENAS: tabelas, constraints e indices. Nenhum INSERT de dado
--     de negocio - o banco nasce vazio e engorda pelo uso.
--   * Identificadores todos em snake_case minusculo, SEM aspas: e assim que o
--     PostgreSQL dobra nomes nao-citados e que o Hibernate (naming strategy
--     padrao do Spring) gera as queries. Nada de nomes maiusculos/citados.
--   * Nenhuma tabela usa palavra reservada do PostgreSQL (a tabela de usuarios
--     chama-se "usuario", nunca "user").
--   * Chaves primarias: bigint GENERATED BY DEFAULT AS IDENTITY, casando com
--     GenerationType.IDENTITY das entidades JPA.
--   * Datas: timestamp SEM time zone - as entidades usam LocalDateTime
--     (horario civil local, sem conversao de fuso) de forma consistente.
--   * Enums Java (@Enumerated(STRING)) viram varchar com o mesmo limite das
--     entidades.
--
-- O Hibernate roda com ddl-auto=validate: se este schema divergir das
-- entidades, o boot aborta - e o comportamento desejado.
-- ============================================================================

-- ===== Catalogo: hierarquia Area -> Subcategoria -> Material (RF17) =====

CREATE TABLE area (
    id        bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome      varchar(100) NOT NULL,
    sigla     varchar(5)   NOT NULL,
    descricao varchar(255),
    CONSTRAINT uk_area_nome  UNIQUE (nome),
    CONSTRAINT uk_area_sigla UNIQUE (sigla)
);

CREATE TABLE subcategoria (
    id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome                varchar(100) NOT NULL,
    sigla               varchar(5)   NOT NULL,
    area_id             bigint       NOT NULL,
    -- Contador do SKU (RF18); manipulado sob lock pessimista pelo
    -- SkuGeneratorService (SELECT ... FOR UPDATE).
    proximo_sequencial  integer      NOT NULL,
    descricao           varchar(255),
    CONSTRAINT fk_subcategoria_area FOREIGN KEY (area_id) REFERENCES area (id),
    -- RN11: sigla unica DENTRO da area.
    CONSTRAINT uk_subcategoria_area_sigla UNIQUE (area_id, sigla)
);

CREATE INDEX idx_subcategoria_area ON subcategoria (area_id);

CREATE TABLE material (
    id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome             varchar(150) NOT NULL,
    -- RF18: SKU e a identidade fisica do produto (etiqueta impressa).
    -- UNIQUE e a defesa final contra duplicidade de codigo.
    codigo_sku       varchar(50),
    unidade_medida   varchar(30),
    estoque_atual    integer      NOT NULL,
    estoque_minimo   integer      NOT NULL,
    valor_unitario   numeric(12, 2),
    subcategoria_id  bigint       NOT NULL,
    CONSTRAINT fk_material_subcategoria FOREIGN KEY (subcategoria_id) REFERENCES subcategoria (id),
    CONSTRAINT uk_material_codigo_sku UNIQUE (codigo_sku)
);

CREATE INDEX idx_material_subcategoria ON material (subcategoria_id);

-- ===== Setores / centros de custo (RF04) =====

CREATE TABLE setor (
    id                   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome                 varchar(120) NOT NULL,
    responsavel          varchar(120) NOT NULL,
    codigo_centro_custo  varchar(30)
);

-- ===== Movimentacoes de estoque (RF06/RF13/RN03/RN04) =====

CREATE TABLE movimentacao (
    id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data              timestamp    NOT NULL,
    tipo              varchar(20)  NOT NULL,   -- ENTRADA | SAIDA | COMPRA_DIRETA
    material_id       bigint       NOT NULL,
    quantidade        integer      NOT NULL,
    setor_destino_id  bigint,                  -- obrigatorio p/ SAIDA (validado no service)
    retirado_por      varchar(120),
    fornecedor        varchar(150),
    nota_fiscal       varchar(50),
    status            varchar(25)  NOT NULL,   -- PENDENTE_APROVACAO | APROVADO | ENTREGUE | REJEITADO
    CONSTRAINT fk_movimentacao_material FOREIGN KEY (material_id) REFERENCES material (id),
    CONSTRAINT fk_movimentacao_setor    FOREIGN KEY (setor_destino_id) REFERENCES setor (id)
);

CREATE INDEX idx_movimentacao_material ON movimentacao (material_id);
CREATE INDEX idx_movimentacao_setor    ON movimentacao (setor_destino_id);
CREATE INDEX idx_movimentacao_data     ON movimentacao (data);

-- ===== Modulo de compras (RF14/RF16) =====

CREATE TABLE compra (
    id                    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data_solicitacao      timestamp    NOT NULL,
    data_recebimento      timestamp,
    tipo                  varchar(15)  NOT NULL,   -- ESTOQUE | DIRETA
    setor_solicitante_id  bigint,                  -- obrigatorio p/ DIRETA (RN08, validado no service)
    observacao            varchar(200),
    fornecedor            varchar(150),
    valor_estimado        numeric(12, 2) NOT NULL,
    valor_real_final      numeric(12, 2),
    numero_nota_fiscal    varchar(50),
    status                varchar(25)  NOT NULL,   -- AGUARDANDO_COMPRA | COMPRA_REALIZADA | CANCELADA
    CONSTRAINT fk_compra_setor FOREIGN KEY (setor_solicitante_id) REFERENCES setor (id)
);

CREATE INDEX idx_compra_setor  ON compra (setor_solicitante_id);
CREATE INDEX idx_compra_status ON compra (status);

CREATE TABLE item_compra (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    compra_id       bigint         NOT NULL,
    material_id     bigint         NOT NULL,
    quantidade      integer        NOT NULL,
    valor_unitario  numeric(12, 2) NOT NULL,
    CONSTRAINT fk_item_compra_compra   FOREIGN KEY (compra_id)   REFERENCES compra (id),
    CONSTRAINT fk_item_compra_material FOREIGN KEY (material_id) REFERENCES material (id)
);

CREATE INDEX idx_item_compra_compra   ON item_compra (compra_id);
CREATE INDEX idx_item_compra_material ON item_compra (material_id);

-- Metadados dos PDFs anexados; o binario fica em disco (volume de uploads),
-- nunca no banco.
CREATE TABLE anexo_compra (
    id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    compra_id           bigint       NOT NULL,
    tipo                varchar(20)  NOT NULL,   -- SOLICITACAO | NOTA_FISCAL
    nome_original       varchar(255) NOT NULL,
    caminho_armazenado  varchar(500) NOT NULL,
    content_type        varchar(100),
    tamanho_bytes       bigint,
    data_upload         timestamp    NOT NULL,
    CONSTRAINT fk_anexo_compra_compra FOREIGN KEY (compra_id) REFERENCES compra (id)
);

CREATE INDEX idx_anexo_compra_compra ON anexo_compra (compra_id);

-- ===== Usuarios (autenticacao) =====
-- "usuario", nao "user": user e palavra reservada no PostgreSQL.

CREATE TABLE usuario (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome        varchar(120) NOT NULL,
    username    varchar(40)  NOT NULL,
    senha_hash  varchar(100) NOT NULL,
    perfil      varchar(15)  NOT NULL,   -- ADMIN | PADRAO
    ativo       boolean      NOT NULL,
    criado_em   timestamp    NOT NULL,
    CONSTRAINT uk_usuario_username UNIQUE (username)
);
