-- ============================================================================
-- V2 - Melhorias trazidas da branch master:
--        * movimentacao passa a ser CABECALHO + ITENS (movimentacao_item);
--        * trilha de auditoria (auditoria_log);
--        * colunas de auditoria tecnica (criado_em/por, atualizado_em/por)
--          em material e movimentacao;
--        * indices de apoio as novas consultas de relatorio.
--
-- Mesmas regras da V1: snake_case sem aspas, identity para PK, timestamp sem
-- time zone. O Hibernate roda com ddl-auto=validate - divergencia derruba o boot.
--
-- Esta migration PRESERVA dados: as movimentacoes existentes (1 material por
-- linha) sao convertidas em uma linha de movimentacao_item antes de as colunas
-- material_id / quantidade serem removidas.
-- ============================================================================

-- ===== Itens da movimentacao =====

CREATE TABLE movimentacao_item (
    id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    movimentacao_id  bigint  NOT NULL,
    material_id      bigint  NOT NULL,
    quantidade       integer NOT NULL,
    -- Snapshot do valor unitario no momento da movimentacao (opcional).
    valor_unitario   numeric(12, 2),
    CONSTRAINT fk_movitem_movimentacao FOREIGN KEY (movimentacao_id) REFERENCES movimentacao (id),
    CONSTRAINT fk_movitem_material     FOREIGN KEY (material_id)     REFERENCES material (id)
);

CREATE INDEX idx_movitem_movimentacao ON movimentacao_item (movimentacao_id);
CREATE INDEX idx_movitem_material     ON movimentacao_item (material_id);

-- Converte o modelo antigo (1 material por movimentacao) no novo. Em um banco
-- recem-criado pela V1 nao ha linhas e o INSERT simplesmente nao move nada.
INSERT INTO movimentacao_item (movimentacao_id, material_id, quantidade, valor_unitario)
SELECT m.id, m.material_id, m.quantidade, mat.valor_unitario
  FROM movimentacao m
  JOIN material mat ON mat.id = m.material_id;

DROP INDEX IF EXISTS idx_movimentacao_material;

ALTER TABLE movimentacao DROP CONSTRAINT IF EXISTS fk_movimentacao_material;
ALTER TABLE movimentacao DROP COLUMN material_id;
ALTER TABLE movimentacao DROP COLUMN quantidade;

-- ===== Colunas novas de movimentacao =====

ALTER TABLE movimentacao ADD COLUMN observacao      varchar(500);
ALTER TABLE movimentacao ADD COLUMN criado_em       timestamp;
ALTER TABLE movimentacao ADD COLUMN criado_por      varchar(120);
ALTER TABLE movimentacao ADD COLUMN atualizado_em   timestamp;
ALTER TABLE movimentacao ADD COLUMN atualizado_por  varchar(120);

CREATE INDEX idx_mov_tipo   ON movimentacao (tipo);
CREATE INDEX idx_mov_status ON movimentacao (status);

-- ===== Auditoria tecnica do material =====

ALTER TABLE material ADD COLUMN criado_em       timestamp;
ALTER TABLE material ADD COLUMN criado_por      varchar(120);
ALTER TABLE material ADD COLUMN atualizado_em   timestamp;
ALTER TABLE material ADD COLUMN atualizado_por  varchar(120);

-- nome e o sort default das listagens de catalogo.
CREATE INDEX idx_material_nome ON material (nome);

-- ===== Ordenacao das listagens de compras =====

CREATE INDEX idx_compra_data_solicitacao ON compra (data_solicitacao);

-- ===== Trilha de auditoria (RF - rastreabilidade de operacoes sensiveis) =====
-- entidade_id e FK LOGICA de proposito: o log sobrevive a exclusao do registro
-- auditado, entao nao pode existir constraint amarrando os dois.

CREATE TABLE auditoria_log (
    id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    timestamp        timestamp    NOT NULL,
    usuario          varchar(120) NOT NULL,
    acao             varchar(40)  NOT NULL,
    entidade         varchar(60)  NOT NULL,
    entidade_id      bigint,
    setor            varchar(120),
    detalhes         varchar(2000),
    ip_origem        varchar(45),
    idempotency_key  varchar(64)
);

CREATE INDEX idx_audit_timestamp ON auditoria_log (timestamp);
CREATE INDEX idx_audit_acao      ON auditoria_log (acao, timestamp);
CREATE INDEX idx_audit_usuario   ON auditoria_log (usuario, timestamp);
CREATE INDEX idx_audit_entidade  ON auditoria_log (entidade, entidade_id);
