-- =============================================================================
-- V4 — Fluxo de aprovacao e compras patrimoniais
--
--  * Perfil COMPRAS (Compras/Almoxarifado): coluna usuario.perfil ja comporta
--    o valor ('COMPRAS' cabe em varchar(15)); nenhuma alteracao de schema.
--  * Autorizacao da Diretoria registrada na pre-compra (PENDENTE | AUTORIZADA |
--    NAO_AUTORIZADA); a baixa so e permitida quando AUTORIZADA.
--  * Compra PATRIMONIAL: itens podem ser descritos livremente (material opcional)
--    e, na baixa, o recebimento e enviado ao sistema de Patrimonio (outbox
--    envio_patrimonio, com reenvio automatico em caso de falha).
-- =============================================================================

ALTER TABLE compra ADD COLUMN autorizacao_diretoria varchar(20) NOT NULL DEFAULT 'PENDENTE';
ALTER TABLE compra ADD COLUMN autorizado_por        varchar(120);
ALTER TABLE compra ADD COLUMN autorizado_em         timestamp;
ALTER TABLE compra ADD COLUMN parecer_diretoria     varchar(500);
ALTER TABLE compra ADD COLUMN retirado_por          varchar(120);
ALTER TABLE compra ADD COLUMN setor_entrega_id      bigint;
ALTER TABLE compra ADD COLUMN enviar_patrimonio     boolean NOT NULL DEFAULT false;
ALTER TABLE compra ADD COLUMN recebido_por          varchar(120);
ALTER TABLE compra ADD CONSTRAINT fk_compra_setor_entrega
    FOREIGN KEY (setor_entrega_id) REFERENCES setor (id);
CREATE INDEX idx_compra_autorizacao ON compra (autorizacao_diretoria);

-- Compras ja realizadas antes desta versao ja passaram pela diretoria.
UPDATE compra SET autorizacao_diretoria = 'AUTORIZADA' WHERE status = 'COMPRA_REALIZADA';

-- Itens patrimoniais nao apontam para o catalogo de consumo.
ALTER TABLE item_compra ALTER COLUMN material_id DROP NOT NULL;
ALTER TABLE item_compra ADD COLUMN descricao varchar(255);

-- Outbox da integracao com o Patrimonio
CREATE TABLE envio_patrimonio (
    id                   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    compra_id            bigint       NOT NULL,
    status               varchar(15)  NOT NULL,   -- PENDENTE | ENVIADO | ERRO
    tentativas           integer      NOT NULL DEFAULT 0,
    ultimo_erro          varchar(1000),
    id_externo           varchar(60),
    criado_em            timestamp    NOT NULL,
    ultima_tentativa_em  timestamp,
    enviado_em           timestamp,
    CONSTRAINT fk_envio_patrimonio_compra FOREIGN KEY (compra_id) REFERENCES compra (id),
    CONSTRAINT uk_envio_patrimonio_compra UNIQUE (compra_id)
);
CREATE INDEX idx_envio_patrimonio_status ON envio_patrimonio (status);
